"""Informe reproducible. Requiere reportlab y Pillow; render de revisión con PyMuPDF."""
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from PIL import Image as PILImage

base=Path(__file__).resolve().parents[1]
destino=base/'output/pdf/Informe_Pomora_GR06_1BT3_622_26B.pdf'
destino.parent.mkdir(parents=True,exist_ok=True)
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='Texto',fontName='Helvetica',fontSize=11,leading=16,spaceAfter=12,textColor=colors.HexColor('#453e50')))
styles['Heading1'].textColor=colors.HexColor('#79589c')
styles['Title'].textColor=colors.HexColor('#29243b')
story=[]
def p(t): story.append(Paragraph(t,styles['Texto']))
def h(t): story.append(Paragraph(t,styles['Heading1'])); story.append(Spacer(1,10))
def nueva(): story.append(PageBreak())
def imagen(ruta,maxalto=460,maxancho=480):
    ruta=base/ruta
    with PILImage.open(ruta) as im: w,h=im.size
    escala=min(maxancho/w,maxalto/h)
    story.append(Image(str(ruta),width=w*escala,height=h*escala));story.append(Spacer(1,12))
story.append(Spacer(1,55));story.append(Paragraph('Pomora',styles['Title']))
story.append(Paragraph('Implementación del Proceso Unificado',styles['Heading1']))
p('<b>Tarea 3 - Grupo 06 - GR06_1BT3_622_26B</b>')
p('Java Web con JSP, Servlet y ORM Hibernate/JPA. Dos incrementos funcionales: Pomodoro individual y emparejamiento para estudio compartido.')
p('Informe de implementación y trazabilidad. Fecha: 3 de octubre de 2026, hora de Colombia.')
p('Asistencia de desarrollo: Codex. Se utilizó el modelo aportado por el grupo; no se atribuye el desarrollo a GitHub Copilot.')
p('Repositorio público: <link href="https://github.com/MayerliChavez/GR06_1BT3_622_26B">MayerliChavez/GR06_1BT3_622_26B</link>')
p('La ampliación de cuentas necesaria para registro y autenticación se autorizó expresamente y se diferencia de las operaciones dibujadas en el modelo de clases original.')
nueva();h('1. Entorno e implementación')
p('Se preparó un proyecto Maven WAR con Java 17 como nivel de compilación, Jetty 12.0.35, Servlet 6, JSP/JSTL, Hibernate 6.6.58.Final y H2 2.3.232. En el equipo de desarrollo se usó el JDK 25 existente. Maven 3.9.11 se instala localmente sin alterar el PATH global.')
p('Las vistas JSP presentan formularios y estado. Los Servlet adaptan las solicitudes HTTP; los servicios coordinan las operaciones funcionales; las entidades implementan las reglas del modelo y los repositorios JPA guardan sus composiciones. ConfiguracionPomodoro es embebida, sin tabla ni identidad independiente.')
p('El inicio normal se ejecuta con iniciar.cmd y abre la pantalla de ingreso. iniciar-radmin.ps1 detecta la dirección del adaptador VPN y permite las pruebas con compañeros. El firewall se limita al puerto TCP 8080 y a las IP individuales indicadas por el anfitrión.')
p('Cuentas, estudiantes, sesiones, bloques y participaciones se almacenan en data/pomora.mv.db. La cola de emparejamiento es temporal. Datos locales, herramientas, logs y archivos compilados no se publican en Git.')
h('2. Trazabilidad del incremento 1')
p('<b>CU01 - Iniciar:</b> PomodoroServlet invoca ServicioPomodoro.iniciarSesion; SesionEstudio crea el bloque mediante iniciarSiguienteBloque. El bloque inicial es de concentración y dura 25 minutos.')
p('<b>CU02 - Pausar:</b> pausarTemporizador delega en SesionEstudio.pausar y BloquePomodoro.pausar; conserva el tiempo activo acumulado y detiene el tramo actual.')
p('<b>CU03 - Reanudar:</b> reanudarTemporizador delega en reanudar. El nuevo tramo comienza en el instante recibido sin sumar el intervalo pausado.')
p('<b>CU04 - Historial:</b> consultarHistorial usa buscarPorEstudiante. La JSP muestra estado, bloques, fechas y tiempo de concentración de la cuenta autenticada.')
nueva();h('3. Trazabilidad del incremento 2')
p('<b>CU01 - Registrar usuario:</b> acceso.jsp solicita nombre, correo y contraseña. AccesoServlet llama a ServicioCuentas.registrar; valida los datos y el correo único normalizado, deriva el hash y guarda CuentaUsuario con su Estudiante. Muestra confirmación y el formulario de ingreso.')
p('<b>CU02 - Iniciar sesión:</b> ServicioCuentas.autenticar consulta por correo y compara el hash. AccesoServlet crea una nueva sesión HTTP autenticada y abre estudio compartido. AccesoFilter impide acceder a las pantallas de estudio sin ingresar.')
p('<b>CU03 - Emparejar:</b> solicitarEmparejamiento usa Emparejador.buscarOEsperar para elegir aleatoriamente otro estudiante disponible y retirar ambas solicitudes. Crea SesionCompartida, dos SesionEstudio y dos ParticipacionCompartida; iniciar comienza los bloques con el mismo instante.')
p('RepositorioSesionesCompartidasJpa guarda toda la composición en una transacción. Las sesiones individuales continúan siendo consultables en el historial. Los nombres se recuperan de las cuentas para evitar sobrescribirlos con el nombre genérico del modelo inicial.')
p('La pantalla consulta cada 3 segundos. actualizarSesion delega en avanzarSiCorresponde, completa bloques vencidos y comienza los siguientes desde el instante real de vencimiento. Ambos temporizadores conservan el mismo ritmo aunque una consulta llegue tarde.')
p('salir y registrarDesconexion registran el motivo en la participación. El compañero puede continuar. Cuando nadie permanece, la compartida queda CERRADA o ABANDONADA si ambas salidas fueron desconexiones. El detector técnico registra desconexión tras 90 segundos sin señales y revisa cada 10 segundos.')
h('4. Fidelidad y ampliación autorizada')
p('Se conservan los 30 métodos funcionales del primer diagrama y se implementan las 19 operaciones nuevas del segundo, incluidas iniciarBloquesSiguientes y finalizar como privadas en SesionCompartida. No se cuentan getters, constructores ni adaptaciones técnicas como operaciones funcionales.')
p('La entidad CuentaUsuario aparece en robustez y sus datos en actividades, pero faltaba en el diagrama de clases. La solicitud posterior del usuario autorizó incorporarla junto a registrar(String, String, String): CuentaUsuario y autenticar(String, String): Optional&lt;CuentaUsuario&gt;. Son dos operaciones adicionales declaradas expresamente, no operaciones atribuidas al diagrama original.')
nueva();h('5. Verificación y resultados')
p('<b>18 pruebas Java aprobadas:</b> pausas y tiempos, ciclos concentración/descanso, estados inválidos, finalización y abandono, composición JPA, orden e historial, prevención de sesiones activas duplicadas, sincronización compartida, salidas y desconexión por ausencia de señales, cuentas únicas, hash con sal, autenticación y persistencia de nombres.')
p('<b>34 comprobaciones HTTP aprobadas:</b> 6 de acceso, 13 de estudio compartido y 15 del incremento individual. Se usaron cuentas independientes para comprobar emparejamiento, nombres visibles, temporizadores comunes, cancelación, salida, historial y rechazo de modificaciones ajenas o sin CSRF válido.')
p('Las pruebas de dominio usan H2 en memoria y tiempos simulados. La aplicación conserva la duración real de 25 minutos; no se esperó un ciclo completo de 25 minutos para estas verificaciones.')
p('La contraseña se guarda como PBKDF2-HMAC-SHA256 con 600000 iteraciones y sal aleatoria de 16 bytes. Referencia: <link href="https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html">OWASP Password Storage Cheat Sheet</link>. La identidad procede de la sesión del servidor y los nombres se escapan al mostrarse.')
p('Las imágenes siguientes son capturas reales del desarrollo. Las imágenes del incremento 1 corresponden a la primera versión; registro y autenticación sustituyen su identidad anónima en la versión final.')
imagen('docs/evidencias/02-temporizador-pausado.jpg',280)
p('<b>Figura 1.</b> Pausa del temporizador individual conservando el tiempo restante.')
nueva();h('6. Evidencias de funcionamiento')
imagen('docs/evidencias/04-historial.jpg',280)
p('<b>Figura 2.</b> Historial individual con detalle de los bloques persistidos.')
imagen('docs/evidencias/07-busqueda-companero.jpg',280)
p('<b>Figura 3.</b> Solicitud en espera de otro estudiante disponible.')
nueva();h('7. Registro e inicio de sesión')
imagen('docs/evidencias/08-inicio-sesion.jpg',285)
p('<b>Figura 4.</b> Primera pantalla: ingreso con correo y contraseña.')
imagen('docs/evidencias/09-registro.jpg',285)
p('<b>Figura 5.</b> Registro con nombre visible, correo y contraseña.')
nueva();h('8. Diagramas originales y reproducibilidad')
p('Los modelos originales se conservan en docs/modelos. Los cuadros de secuencia vacíos de la primera imagen no se presentan como secuencias completas. La trazabilidad se apoya en las clases, actividades y robustez disponibles.')
p('Compilar: mvnw.cmd package. Pruebas HTTP con el servidor iniciado: scripts/verificar-acceso.ps1, verificar-compartido.ps1 y verificar-web.ps1, pasando -BaseUrl con la dirección del servidor.')
p('La auditoría detallada está en docs/AUDITORIA-METODOS.md; la trazabilidad individual en docs/TRAZABILIDAD.md; la compartida y la ampliación de cuentas en docs/INCREMENTO2.md; los resultados en docs/VERIFICACION.md.')
imagen('docs/modelos/incremento1-clases.jpg',470)
p('<b>Figura 6.</b> Diagrama de clases original del incremento 1.')
nueva();h('9. Modelo de estudio compartido')
imagen('docs/modelos/incremento2-clases.jpg',600)
p('<b>Figura 7.</b> Diagrama de clases original del incremento 2, conservado sin alteraciones. CuentaUsuario y ServicioCuentas se documentan como ampliación autorizada.')
def pie(canvas,doc):
    canvas.setStrokeColor(colors.HexColor('#ded7e6'));canvas.line(48,42,547,42)
    canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#77717e'))
    canvas.drawString(48,28,'Pomora | Grupo 06 | Tarea 3');canvas.drawRightString(547,28,str(doc.page))
doc=SimpleDocTemplate(str(destino),pagesize=A4,leftMargin=48,rightMargin=48,topMargin=40,bottomMargin=55,title='Pomora - Informe de implementación',author='Grupo 06')
doc.build(story,onFirstPage=pie,onLaterPages=pie)
print(destino)
